// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYLHb6VKMtRjUrFOb-6Bw-vzgyI3hiJ1o',
    appId: '1:398613761675:web:d5826396c7c45049154e8e',
    messagingSenderId: '398613761675',
    projectId: 'lunari-18e8a',
    authDomain: 'lunari-18e8a.firebaseapp.com',
    storageBucket: 'lunari-18e8a.firebasestorage.app',
    measurementId: 'G-L9Y1Q4ZQQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc3lnIp9mtibL6PaDHGeP4KXoY4p5p6DY',
    appId: '1:398613761675:android:b833f769d3e36025154e8e',
    messagingSenderId: '398613761675',
    projectId: 'lunari-18e8a',
    storageBucket: 'lunari-18e8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOngpwWP-Lc5fbRVkF4dBmh_YE5jpzzLU',
    appId: '1:398613761675:ios:464a32e256ec4a74154e8e',
    messagingSenderId: '398613761675',
    projectId: 'lunari-18e8a',
    storageBucket: 'lunari-18e8a.firebasestorage.app',
    iosBundleId: 'com.example.lunari',
  );
}
